### ISSUE TITLE
Error in test execution

### ISSUE THREAD

**Issue by guilherme-funchal** [openwallet-foundation/owl-agent-test-harness#148]
How I solve this error ?

1 feature passed, 4 failed, 0 skipped
15 scenarios passed, 8 failed, 56 skipped
143 steps passed, 8 failed, 571 skipped, 0 undefined
Took 6m23.121s
2021-01-26 19:02:24,123 aries_cloudagent.core.dispatcher ERROR Handler error: invitation_create
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 73, in invitation_create
    use_public_did=use_public_did,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 92, in create_invitation
    multi_use=multi_use,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 130, in create_invitation
    raise ConnectionManagerError("Public invitations are not enabled")
aries_cloudagent.protocols.connections.v1_0.manager.ConnectionManagerError: Public invitations are not enabled
2021-01-26 19:02:24,125 aries_cloudagent.admin.server ERROR Handler error with exception: Public invitations are not enabled
2021-01-26 19:02:24,125 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 144, in ready_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 177, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 275, in apply_limiter
    return await task
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 73, in invitation_create
    use_public_did=use_public_did,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 92, in create_invitation
    multi_use=multi_use,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 130, in create_invitation
    raise ConnectionManagerError("Public invitations are not enabled")
aries_cloudagent.protocols.connections.v1_0.manager.ConnectionManagerError: Public invitations are not enabled
2021-01-26 19:02:24,100 aries_cloudagent.core.dispatcher ERROR Handler error: invitation_create
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 73, in invitation_create
    use_public_did=use_public_did,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 92, in create_invitation
    multi_use=multi_use,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 130, in create_invitation
    raise ConnectionManagerError("Public invitations are not enabled")
aries_cloudagent.protocols.connections.v1_0.manager.ConnectionManagerError: Public invitations are not enabled
2021-01-26 19:02:24,104 aries_cloudagent.admin.server ERROR Handler error with exception: Public invitations are not enabled
2021-01-26 19:02:24,104 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 144, in ready_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 177, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 275, in apply_limiter
    return await task
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 73, in invitation_create
    use_public_did=use_public_did,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 92, in create_invitation
    multi_use=multi_use,
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 130, in create_invitation
    raise ConnectionManagerError("Public invitations are not enabled")
aries_cloudagent.protocols.connections.v1_0.manager.ConnectionManagerError: Public invitations are not enabled

**Comment by nodlesh** [comment]
The tests that test a Public DID Invitation will fail. There are currently some issues in Aca-py that are being worked on to solve this.

**Comment by swcurran** [comment]
Closing as expected, but we are working on a way to report status so that there is a tighter link between an error and the issue that exists to address the error.

As well, we are going to add tags that allow the bypassing of tests for tags that are not supported, so those tests can be bypassed.
