### ISSUE TITLE
Dotnet backchannel errors for Acapy-Dotnet runset when All interim state checks are removed. 

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#326]
The AATH no longer checks for interim states in protocol progression. In the Issue Credential and Proof tests the Dotnet Agent/Backchannel fails when running with Acapy with these state checks removed. Running with dotnet playing all roles does not produce the errors. There is a call `expected_agent_state()` in the tests where not calling it in two cases, causes the failures. 

**HOW TO REPRODUCE**
Comment out the following lines of code.
`@when('"{issuer}" offers a credential')` on line 254 of `0036-issue-credential.py`.
```
assert expected_agent_state(context.holder_url, "issue-credential", context.cred_thread_id, "offer-received")
```
`@when('"{verifier}" sends a request for proof presentation to "{prover}"')` on line 174 of `0037-present-proof.py`
```
assert expected_agent_state(context.prover_url, "proof", context.presentation_thread_id, "request-received")
```
Run the following commands
```
./manage rebuild -a dotnet-master -a acapy-main
./manage run -d acapy-main -b dotnet-master -t @AcceptanceTest -t ~@wip -t ~@ProofProposal -t ~@RFC0023 -t ~@DIDExchangeConnection
```

**RESULTS**
```
  features/0036-issue-credential.feature:9  Issue a credential with the Holder beginning with a proposal
  features/0036-issue-credential.feature:37  Issue a credential with the Holder beginning with a proposal with negotiation
  features/0036-issue-credential.feature:53  Issue a credential with the Issuer beginning with an offer
  features/0036-issue-credential.feature:66  Issue a credential with the Issuer beginning with an offer with negotiation
  features/0037-present-proof.feature:19  Present Proof where the prover does not propose a presentation of the proof and is acknowledged -- @1.1 
  features/0037-present-proof.feature:20  Present Proof where the prover does not propose a presentation of the proof and is acknowledged -- @1.2 
  features/0037-present-proof.feature:55  Present Proof of specific types and proof is acknowledged with a Drivers License credential type -- @1.1 
  features/0037-present-proof.feature:56  Present Proof of specific types and proof is acknowledged with a Drivers License credential type -- @1.2 
  features/0037-present-proof.feature:74  Present Proof of specific types and proof is acknowledged with a Biological Indicators credential type -- @1.1 
  features/0037-present-proof.feature:91  Present Proof of specific types and proof is acknowledged with multiple credential types -- @1.1 
  features/0037-present-proof.feature:109  Present Proof where the prover does not propose a presentation of the proof and is acknowledged -- @1.1 
  features/0037-present-proof.feature:110  Present Proof where the prover does not propose a presentation of the proof and is acknowledged -- @1.2 
  features/0183-revocation.feature:24  Credential revoked by Issuer and Holder attempts to prove with a prover that doesn't care if it was revoked -- @1.1 
  features/0183-revocation.feature:60  Credential revoked by Issuer and Holder attempts to prove with a prover that doesn't care if it was revoked -- @1.1 
  features/0183-revocation.feature:79  Credential revoked and replaced with a new updated credential, holder proves claims with the updated credential with timesstamp -- @1.1 
  features/0183-revocation.feature:116  Proof in process while Issuer revokes credential before presentation and the verifier doesn't care about revocation status -- @1.1 
  features/0183-revocation.feature:155  Credential is revoked inside the non-revocation interval -- @1.1 
  features/0183-revocation.feature:156  Credential is revoked inside the non-revocation interval -- @1.2 
  features/0183-revocation.feature:157  Credential is revoked inside the non-revocation interval -- @1.3 
  features/0183-revocation.feature:176  Credential is revoked before the non-revocation instant -- @1.1 
  features/0183-revocation.feature:177  Credential is revoked before the non-revocation instant -- @1.2 
  features/0183-revocation.feature:178  Credential is revoked before the non-revocation instant -- @1.3 
  features/0183-revocation.feature:179  Credential is revoked before the non-revocation instant -- @1.4 
  features/0183-revocation.feature:197  Credential is revoked before the non-revocation interval -- @1.1 
  features/0183-revocation.feature:198  Credential is revoked before the non-revocation interval -- @1.2 
  features/0183-revocation.feature:216  Credential is revoked before the non-revocation instant -- @1.1 
  features/0183-revocation.feature:217  Credential is revoked before the non-revocation instant -- @1.2 
  features/0183-revocation.feature:218  Credential is revoked before the non-revocation instant -- @1.3 
  features/0183-revocation.feature:219  Credential is revoked before the non-revocation instant -- @1.4 
  features/0183-revocation.feature:333  Revocable Credential not revoked and Holder attempts to prove without a non-revocation interval -- @1.1 
  features/0183-revocation.feature:350  Non-revocable Credential, not revoked, and holder proves claims with the credential with timesstamp -- @1.1 
  features/0183-revocation.feature:367  Revocable Credential, not revoked, and holder proves claims with the credential with timesstamp -- @1.1 

1 feature passed, 3 failed, 3 skipped
2 scenarios passed, 32 failed, 64 skipped
140 steps passed, 32 failed, 715 skipped, 0 undefined
Took 9m52.072s
```

The Error message in the Dotnet agent/backchannel is 
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMBE6JN9A9ST", Request id "0HMBE6JN9A9ST:00000001": An unhandled exception was thrown by the application.
System.ArgumentException: A value must be provided. (Parameter 'credOfferJson')
   at Hyperledger.Indy.Utils.ParamGuard.NotNullOrWhiteSpace(String param, String paramName)
   at Hyperledger.Indy.AnonCredsApi.AnonCreds.ProverCreateCredentialReqAsync(Wallet wallet, String proverDid, String credOfferJson, String credDefJson, String masterSecretId)
   at Hyperledger.Aries.Features.IssueCredential.DefaultCredentialService.CreateRequestAsync(IAgentContext agentContext, String credentialId) in /aries-framework-dotnet/src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs:line 345
   at DotNet.Backchannel.Controllers.IssueCredentialController.SendCredentialRequestAsync(OperationBody body) in /src/Controllers/IssueCredentialController.cs:line 238
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Hyperledger.Aries.AspNetCore.AgentMiddleware.Invoke(HttpContext aHttpContext, IAgentProvider aAgentProvider) in /aries-framework-dotnet/src/Hyperledger.Aries.AspNetCore/AgentMiddleware.cs:line 40
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by swcurran** [comment]
I think this is now resolved? Closing -- please reopen if there are still issues to address.
